# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Computer_Organization/FeatherCPU/src/FeatherCPU.srcs/sources_1/ip/upg_clk_wiz/upg_clk_wiz.xci
# IP: The module: 'upg_clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Computer_Organization/FeatherCPU/src/FeatherCPU.srcs/sources_1/ip/upg_clk_wiz/upg_clk_wiz.xci
# IP: The module: 'upg_clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Computer_Organization/FeatherCPU/src/FeatherCPU.gen/sources_1/ip/upg_clk_wiz/upg_clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'upg_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
