# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/data_mem/data_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet
