# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/uart0/uart0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart0 || ORIG_REF_NAME==uart0} -quiet] -quiet
